### ISSUE TITLE
Error trying to get BET tokens in Test Network

### ISSUE THREAD

**Issue by walacemaia** [DaoCasino/BankRollerApp#24]
When I click on "get test bets" button, BETS are not credited in the address.

If there is a connectivity problem, there should be a clear message informing the user.

Operating System: Window 10
Ethereum network: Ropsten Test Network
Time of the incident: 27/08/2017 20:05 GMT

**Comment by noxonsu** [comment]
@alexstep

**Comment by alexstep** [comment]
We have some problems with our faucet, someone stole test bets.
Problem solved.
